config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :offers
  resources :item_albums
  resources :comments
  resources :reviews
  devise_for :users
  resources :items

    root 'items#index'
      get 'users/:id' => 'users#show'
      get 'email_user' => 'users#user_to_user',as: :email_user
      get 'items/:id/editpictures' => 'items#editpictures', as: :edit_pics
      get 'username/search'=> 'users#search', as: :username_search

end

app/models/item_album.rb
class ItemAlbum < ActiveRecord::Base
  belongs_to :item
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/item_albums_controller.rb
class ItemAlbumsController < ApplicationController
  before_action :set_item_album, only: [:show, :edit, :update, :destroy]

  # GET /item_albums
  # GET /item_albums.json
  def index
    @item_albums = ItemAlbum.all
  end

  # GET /item_albums/1
  # GET /item_albums/1.json
  def show
  end

  # GET /item_albums/new
  def new
    @item_album = ItemAlbum.new
  end

  # GET /item_albums/1/edit
  def edit
  end

  # POST /item_albums
  # POST /item_albums.json
  def create
    @item_album = ItemAlbum.new(item_album_params)
    @item_album.item_id=params[:item]
    respond_to do |format|
      if @item_album.save
        format.html { redirect_to(:back)  }
        format.json { render :show, status: :created, location: @item_album }
      else
        format.html { render :new }
        format.json { render json: @item_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_albums/1
  # PATCH/PUT /item_albums/1.json
  def update
    respond_to do |format|
      if @item_album.update(item_album_params)
        format.html { redirect_to @item_album, notice: 'Item album was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_album }
      else
        format.html { render :edit }
        format.json { render json: @item_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_albums/1
  # DELETE /item_albums/1.json
  def destroy
    @item_album.destroy
    respond_to do |format|
      format.html { redirect_to(:back)  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_album
      @item_album = ItemAlbum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_album_params
      params.require(:item_album).permit(:item_id,:image)
    end
end

app/helpers/item_albums_helper.rb
module ItemAlbumsHelper
end

app/views/item_albums/_form.html.erb
<%= form_for(@item_album) do |f| %>
  <% if @item_album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_album.errors.count, "error") %> prohibited this item_album from being saved:</h2>

      <ul>
      <% @item_album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <%= f.file_field :image %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_albums/edit.html.erb
<h1>Editing Item Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_album %> |
<%= link_to 'Back', item_albums_path %>

app/views/item_albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Albums</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_albums.each do |item_album| %>
      <tr>
        <td><%= item_album.item_id %></td>
        <td><%= link_to 'Show', item_album %></td>
        <td><%= link_to 'Edit', edit_item_album_path(item_album) %></td>
        <td><%= link_to 'Destroy', item_album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item album', new_item_album_path %>

app/views/item_albums/new.html.erb
<h1>New Item Album</h1>

<%= render 'form' %>

<%= link_to 'Back', item_albums_path %>

app/views/item_albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_album.item_id %>
</p>
<% if @item_album.image.file? %>
  <%= image_tag @item_album.image.url %>
<% end %>

<%= link_to 'Edit', edit_item_album_path(@item_album) %> |
<%= link_to 'Back', item_albums_path %>