config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :offers
  resources :item_albums
  resources :comments
  resources :reviews
  devise_for :users
  resources :items

    root 'items#index'
      get 'users/:id' => 'users#show'
      get 'email_user' => 'users#user_to_user',as: :email_user
      get 'items/:id/editpictures' => 'items#editpictures', as: :edit_pics
      get 'username/search'=> 'users#search', as: :username_search

end

app/models/offer.rb
class Offer < ActiveRecord::Base

  belongs_to :user
  belongs_to :item
  validates :message, length: { in: 5..1000 }


end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = current_user.offers.build
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = current_user.offers.build(offer_params)

    respond_to do |format|
      if @offer.save
        @item=@offer.item.name
        @to=@offer.item.user.email
        @to_username=@offer.item.user.username
        @from_username=@offer.user.username
        @offer=@offer.message
        UserMailer.offer(@item,@to,@to_username,@from_username,@offer).deliver
        format.html { redirect_to page_path('sent_offer') }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:item_id, :user_id, :message)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_hidden">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id,value:params[:item] %>
  </div>

  <div class="field">

    <%= f.text_area :message,placeholder:"Enter Your Message here!" %>
  </div>
  <div class="actions">
    <%= f.submit 'Send Message',class:'offer_button' %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offers</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.item_id %></td>
        <td><%= offer.user_id %></td>
        <td><%= offer.message %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>Send a Message to the Seller</h1>
<div class='new_offer'>
<%= render 'form' %>
<h3>This will send your message to the seller and will give them a chance to reply back to you</h3>
<h3>Watch your email for the reply! Emails will be sent to the Email you provided during signup</h3>
<h4>If you need to change or check what Email you used check <%=link_to 'here!',edit_user_registration_path%>'</h4>
</div>

app/views/offers/show.html.erb
<div id='offer_page'>
  <p id="notice"><%= notice %></p>

  <h1>This offer was sent from <%=@offer.user.username%></h1>
  <h2>It was to inquirer about <%=@offer.item.name%></h2>

  <div id='offer_message'>
    <%= @offer.message %>
  </div>



  <% if user_signed_in? %>
    <div id='email_show'>
      <%= form_tag(email_user_path, method: "get") do %>
        <h2><%= label_tag :message, "Reply to this message here by Emailing #{@offer.user.username}" %></h2>
        <br>
        <%= text_area_tag(:message,nil,:placeholder => 'Add Message') %>
        <%= hidden_field_tag :to_email , @offer.user.email %>
        <%= hidden_field_tag :to , @offer.user.username %>
        <%= hidden_field_tag :from , current_user.username %>
        <%= hidden_field_tag :from_id , current_user.id %>
        <br>
        <%= submit_tag("Send") %>
      <% end %>
      <h2>This message will be sent to <%=@offer.user.username%> </h2>
     </div>
    <%else%>
      <h2><%= link_to('Login', new_user_session_path)%> to send <%= @offer.user.username %> a message </h2>
    <%end%>
</div>